AWSTemplateFormatVersion: '2010-09-09'
Description: >
  IAM roles and policies for ETL pipeline including Lambda, Glue, and Redshift Spectrum, with least privilege access to S3 and Glue Catalog.

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the ETL S3 bucket

  AWSAccountId:
    Type: String
    Description: AWS Account ID (for resource ARNs)

  Region:
    Type: String
    Default: us-east-1
    Description: AWS region

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda_execution_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${Region}:${AWSAccountId}:log-group:/aws/lambda/*

  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue_execution_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Sub arn:aws:s3:::${S3BucketName}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}/raw/*
                  - !Sub arn:aws:s3:::${S3BucketName}/clean/*
        - PolicyName: GlueServicePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                Resource:
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:catalog
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:database/*
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:table/*
        - PolicyName: GluePassRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowPassRoleToSelf
                Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt GlueExecutionRole.Arn
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService: glue.amazonaws.com

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue_crawler_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Sub arn:aws:s3:::${S3BucketName}
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::${S3BucketName}/clean/*
        - PolicyName: GlueCrawlerGlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:CreatePartition
                  - glue:UpdatePartition
                  - glue:BatchCreatePartition
                Resource:
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:catalog
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:database/*
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:table/*

  RedshiftSpectrumAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: redshift_spectrum_access_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: RedshiftSpectrumS3ReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/clean/*
        - PolicyName: RedshiftSpectrumGlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                Resource:
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:catalog
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:database/*
                  - !Sub arn:aws:glue:${Region}:${AWSAccountId}:table/*

Outputs:
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn

  GlueExecutionRoleArn:
    Description: ARN of the Glue job execution role
    Value: !GetAtt GlueExecutionRole.Arn

  GlueCrawlerRoleArn:
    Description: ARN of the Glue Crawler role
    Value: !GetAtt GlueCrawlerRole.Arn

  RedshiftSpectrumAccessRoleArn:
    Description: ARN of the Redshift Spectrum access role
    Value: !GetAtt RedshiftSpectrumAccessRole.Arn
