AWSTemplateFormatVersion: '2010-09-09'
Description: >
  IAM roles and policies for ETL pipeline including Lambda, Glue, and Redshift Spectrum with least privilege.

Resources:

  # Lambda execution role with basic logging permissions only
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda_execution_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  # Glue execution role with scoped S3 and Glue permissions + PassRole
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue_execution_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # List bucket permission for pipeline bucket
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::
              # Read/write/delete objects in raw and clean folders
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::your-bucket/raw/*
                  - arn:aws:s3:::your-bucket/clean/*
        - PolicyName: GlueServicePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:CreateJob
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                Resource: "*"
        - PolicyName: GluePassRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow Glue to pass this execution role when starting jobs
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt GlueExecutionRole.Arn

  # Glue Crawler Role with S3 access to "clean" folder and Glue permissions
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue_crawler_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::your-bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::your-bucket/clean/*
        - PolicyName: GlueCrawlerGlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: glue:*
                Resource: "*"

  # Redshift Spectrum Access Role with read-only S3 + Glue catalog access
  RedshiftSpectrumAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: redshift_spectrum_access_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: RedshiftSpectrumS3ReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Read-only access to the ETL pipeline bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::your-bucket
                  - arn:aws:s3:::your-bucket/clean/*
        - PolicyName: RedshiftSpectrumGlueCatalogAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Glue catalog access for Redshift Spectrum queries
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                Resource: "*"
